web:
  image: openresty/openresty:alpine
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./config/conf.d:/etc/nginx/conf.d
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./code:/code