version: '3'

services:
    nginx:
        image: nginx:1.14.2-alpine
        ports:
            - "8080:80"
        volumes:
          - ./conf.d:/etc/nginx/conf.d
          - ./log:/var/log/nginx
          - ./www:/var/www
          - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - code-network
        container_name: nginx # 容器名称
    php:
        image: php:7.3-fpm
        volumes:
            - ./code:/code
            - ./php-fpm.d/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - ./php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - code-network
        container_name: php # 容器名称    

networks:
    code-network:
        driver: bridge
volumes:
    phpsocket: