version: '3'

services:
    nginx:
        image: nginx:1.14.2-alpine
        ports:
            - 8080:80
            - 443:443
        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf # 修改默认配置文件
          - ./conf/conf.d:/etc/nginx/conf.d
          - ./log:/var/log/nginx
          - ./www:/var/www
          - /etc/letsencrypt:/etc/letsencrypt
        restart: always  
        container_name: lnmp-nginx-v1 # 容器名称
        networks:
            - code-network
    php:
        image: php:7.3-fpm
        volumes:
            - ./www:/var/www
            - ./etc/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - ./etc/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - code-network
        container_name: lnmp-php-v1 # 容器名称   

networks:
    code-network:
        driver: bridge
volumes:
    phpsocket:        