version: '3'

services:
    lnmp-nginx:
        depends_on:
            - lnmp-php
        image: nginx:1.14.2-alpine
        ports:
            - 8088:8088
            - 443:443
        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf # 修改默认配置文件
          - ./conf/conf.d:/etc/nginx/conf.d
          - ./log:/var/log/nginx
          - ./www:/var/www
          - ./etc/letsencrypt:/etc/letsencrypt
        restart: always  
        container_name: lnmp-nginx-v6 # 容器名称
        networks:
            - frontend
    lnmp-php:
        depends_on:
            - lnmp-mysql
            - lnmp-redis
        image: tinywan/lnmp:php7.2.13-v1
        volumes:
            - ./www:/var/www
            - ./etc/php.ini:/usr/local/php/etc/php.ini
            - ./etc/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - ./etc/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - frontend
            - backend    
        container_name: lnmp-php7.2-v6 # 容器名称   
    lnmp-mysql:
        image: mysql:5.7
        hostname: lnmp-mysql-v6
        ports:
            - "3308:3308"
        volumes:
            - ./etc/mysql/data:/var/lib/mysql
            - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: 123456    
        networks:
            - backend
        restart: always
        container_name: lnmp-mysql-v6
    lnmp-redis:
        image: redis:5.0-alpine
        hostname: lnmp-redis-v6
        ports:
            - "63789:63789"
        command: redis-server /usr/local/etc/redis/redis.conf    
        networks:
            - backend      
        volumes:
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./log/redis.log:/data/redis.log
        restart: always
        container_name: lnmp-redis-v6
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge   