version: '3'

services:
    mysql :
        build :
            context : ./mysql5.7
            dockerfile : Dockerfile
        ports :
            - "3308:3306"
        volumes :
            - ./var/mysql/data:/var/lib/mysql
        #初始密码
        environment :
            - MYSQL_ROOT_PASSWORD=123456
        container_name : mysql5.7-v2
        restart : always  
    php-fpm :
        build :
            context : ./php7
            dockerfile : Dockerfile
        ports :
            - "9000:9000"
        volumes :
            - ./www:/var/www
            - ./etc/php.ini:/usr/local/php7/lib/php.ini:ro
            - ./etc/php-fpm.conf:/usr/local/php7/etc/php-fpm.conf
            - ./etc/php-fpm.d/www.conf:/usr/local/php7/etc/php-fpm.d/www.conf
        container_name : php-fpm-7.2-v2
        links :
            - mysql
        restart : always 
    nginx:
        image: nginx:1.14.2-alpine
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf # 修改默认配置文件
            - ./conf/conf.d:/etc/nginx/conf.d
            - ./log:/var/log/nginx
            - ./www:/var/www
            - ./var/run:/var/run
            - ./etc/letsencrypt:/etc/letsencrypt
        restart: always  
        container_name: nginx-1.14.2-alpine-v2 # 容器名称
        links:
            - php-fpm 
    redis :
        image : redis
        container_name : redis-v2
        volumes :
            - ./var/redis/data:/data
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports :
            - 63799:6379
        command : redis-server /usr/local/etc/redis/redis.conf
        restart: always            